openapi: 3.0.3
info:
  title: E-Commerce Order API
  description: Order management API
  version: 1.0.0

servers:
  - url: http://localhost:8082/api/v1/orders

paths:
  /:
    post:
      operationId: createOrder
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request
        '409':
          description: Conflict (e.g., insufficient stock)

  /{orderId}:
    get:
      operationId: getOrder
      summary: Get order details
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

  /user/{userId}:
    get:
      operationId: listUserOrders
      summary: List user's orders
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'

  /{orderId}/cancel:
    post:
      operationId: cancelOrder
      summary: Cancel an order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelOrderRequest'
      responses:
        '200':
          description: Order cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Cannot cancel order
        '404':
          description: Order not found

  /{orderId}/status:
    get:
      operationId: getOrderStatus
      summary: Get order status
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatus'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        orderNumber:
          type: string
        userId:
          type: string
        status:
          type: string
          enum: [pending, confirmed, processing, shipped, delivered, cancelled, refunded]
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        subtotal:
          type: number
        tax:
          type: number
        shippingCost:
          type: number
        discount:
          type: number
        total:
          type: number
        currency:
          type: string
        notes:
          type: string
        trackingNumber:
          type: string
        estimatedDelivery:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    OrderItem:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        variantId:
          type: string
        name:
          type: string
        sku:
          type: string
        price:
          type: number
        quantity:
          type: integer
        subtotal:
          type: number
        imageUrl:
          type: string

    Address:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        company:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
        phone:
          type: string

    PaymentMethod:
      type: object
      properties:
        type:
          type: string
          enum: [card, paypal, bank_transfer, cod]
        last4:
          type: string
        brand:
          type: string
        expiryMonth:
          type: integer
        expiryYear:
          type: integer

    CreateOrderRequest:
      type: object
      required:
        - userId
        - shippingAddress
        - paymentMethodId
      properties:
        userId:
          type: string
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'
        paymentMethodId:
          type: string
        shippingMethod:
          type: string
        couponCode:
          type: string
        notes:
          type: string

    CancelOrderRequest:
      type: object
      properties:
        reason:
          type: string

    OrderStatus:
      type: object
      properties:
        orderId:
          type: string
        status:
          type: string
        statusHistory:
          type: array
          items:
            $ref: '#/components/schemas/StatusHistoryEntry'
        trackingNumber:
          type: string
        estimatedDelivery:
          type: string
          format: date-time

    StatusHistoryEntry:
      type: object
      properties:
        status:
          type: string
        timestamp:
          type: string
          format: date-time
        description:
          type: string

    OrderListResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
