openapi: 3.0.3
info:
  title: E-Commerce Cart API
  description: Shopping cart management API
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/v1/cart

paths:
  /{userId}:
    get:
      operationId: getCart
      summary: Get user's cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User's shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    delete:
      operationId: clearCart
      summary: Clear cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cart cleared

  /{userId}/items:
    post:
      operationId: addToCart
      summary: Add item to cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddToCartRequest'
      responses:
        '200':
          description: Updated cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Invalid request
        '409':
          description: Insufficient stock

  /{userId}/items/{itemId}:
    put:
      operationId: updateCartItem
      summary: Update cart item quantity
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCartItemRequest'
      responses:
        '200':
          description: Updated cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    delete:
      operationId: removeFromCart
      summary: Remove item from cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Updated cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /{userId}/validate:
    post:
      operationId: validateCart
      summary: Validate cart for checkout
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartValidationResult'

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        subtotal:
          type: number
        tax:
          type: number
        discount:
          type: number
        total:
          type: number
        currency:
          type: string
        itemCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    CartItem:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        variantId:
          type: string
        name:
          type: string
        sku:
          type: string
        price:
          type: number
        quantity:
          type: integer
        subtotal:
          type: number
        imageUrl:
          type: string
        attributes:
          type: object

    AddToCartRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
        variantId:
          type: string
        quantity:
          type: integer
          minimum: 1

    UpdateCartItemRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          minimum: 0

    CartValidationResult:
      type: object
      properties:
        valid:
          type: boolean
        issues:
          type: array
          items:
            $ref: '#/components/schemas/ValidationIssue'

    ValidationIssue:
      type: object
      properties:
        itemId:
          type: string
        type:
          type: string
          enum: [out_of_stock, price_changed, item_unavailable]
        message:
          type: string
        currentStock:
          type: integer
        currentPrice:
          type: number
